### ISSUE TITLE
Product page: Stats table

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#100]
<img width="1423" alt="Screenshot 2023-06-23 at 11 05 33 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/5da1b96d-bd35-4021-aa1e-492905df0ad8">
<img width="1348" alt="Screenshot 2023-06-23 at 11 06 46 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/02ef034e-cb94-454f-b319-36c3b53c8267">

Should be a section with a stats table and text.

**Comment by tmathern** [comment]
Make sure that the table uses the logos (images) in the first column, and that theming is applied.

**Comment by atopper** [comment]
Starting on this one.
