### ISSUE TITLE
Product pages: decorative banners

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#107]
Variant 1: Symetrical banners on left and right
<img width="1565" alt="2-borders-1" src="https://github.com/hlxsites/sgws-creative/assets/60901087/1c0f0228-6912-4948-9644-963283addadd">
<img width="1569" alt="2-borders-2" src="https://github.com/hlxsites/sgws-creative/assets/60901087/0e46e598-c1ba-4e45-9075-8c7134af94c0">
<img width="1569" alt="2-borders-3" src="https://github.com/hlxsites/sgws-creative/assets/60901087/a2f660c7-5a56-400f-bcdc-e63746a30b2b">

Variant 2: One long banner
<img width="1569" alt="1-border-1" src="https://github.com/hlxsites/sgws-creative/assets/60901087/e457f89d-5ebe-4f86-b3cc-4901ffedc6de">
<img width="1569" alt="1-border-2" src="https://github.com/hlxsites/sgws-creative/assets/60901087/f79594cc-9036-45a3-a769-c24dc13d31a4">

Variant 3: One long banner with content overlap
<img width="1569" alt="1-border-overlap" src="https://github.com/hlxsites/sgws-creative/assets/60901087/7ba645b9-6b0e-4021-9de1-f71e81466fc6">

**Comment by tmathern** [comment]
<img width="1565" alt="2-borders-4" src="https://github.com/hlxsites/sgws-creative/assets/60901087/5ab6907a-8430-4ed9-b1d1-11d0847f9843">
The banners left and right contain two images, but we'll merge them so we can rely on variant 1 to draw the banners.

**Comment by atopper** [comment]
Note that some are symmetrical, while others are not.
And note that one like the ruffino grapes are created using 4 images per side.

**Comment by atopper** [comment]
[grape_banner.zip](https://github.com/hlxsites/sgws-creative/files/12020391/grape_banner.zip)

**Comment by atopper** [comment]
To make this authorable, I think there has to be an ordered series of images (as many as they want) and each one has values for:
- canvas flip horizontal
- canvas flip vertical
- x axis (unit?) from left or right
- y axis (unit?)
The section itself takes up no rendered space and has a z-index above the other elements.

**Comment by tmathern** [comment]
I would have two cases:
- one image left + one right ("merged down" images of all layers on each side)
- one banner for the whole width
And use those images. This leaves enough room for a designer to create the proper images in Photoshop (for instance). Wdyt?
