### ISSUE TITLE
Comparison stats variant

### ISSUE THREAD

**Issue by badvision** [hlxsites/sgws-creative#122]
Variant 1:
This feature should reproduce the second tab of this page: https://sgcreative.southernglazers.com/bloominbrands/p/6

![image](https://github.com/hlxsites/sgws-creative/assets/5144198/a39a34e5-578e-43bf-ac6a-591d45648111)

Authoring experience:
<img width="673" alt="Screenshot 2023-07-18 at 3 44 42 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/87ae5bd7-392f-40a3-9b18-5db711b00fc6">

**Comment by tmathern** [comment]
<img width="1323" alt="Screenshot 2023-07-18 at 9 36 14 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/c1ec1bb6-2c7b-47c7-9e4c-a72f525ea346">

**Comment by tmathern** [comment]
Replaced by https://github.com/hlxsites/sgws-creative/issues/161 and https://github.com/hlxsites/sgws-creative/issues/160
