### ISSUE TITLE
Some components are invisible on product pages

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#126]
Some components are invisible on product pages, like for instance the columns "who we are in https://main--sgws-creative--hlxsites.hlx.page/drafts/komenda/edisco.

This seems to be related to an opacity value set to 0 that is not updated for product pages (the content _is_ here). 
All blocks should be visible and usable on product pages too.

**Comment by atopper** [comment]
@tmathern Where is the original page (i.e. in https://sgcreative.southernglazers.com/).  I can't seem to find it.
I'm wondering if the theme (edisco.xslx) will actually be found as it is currently implemented ([here](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/drafts/[komenda](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/drafts/komenda?csf=1&web=1&e=mcDqGb)?csf=1&web=1&e=mcDqGb))
