### ISSUE TITLE
Remove “Designed by...” logo in the footer.

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#127]
<img width="1662" alt="Screenshot 2023-07-11 at 3 32 19 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/a94d942e-b44f-4464-b8dc-19f4e98288da">

**Comment by sarav-sgws** [comment]
This is content issue. Removed the footer image from https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BAA20CFD6-558E-435E-8B23-638B92861DB6%7D&file=footer.docx&action=default&mobileredirect=true and published. 

Ready to retest.

**Comment by sarav-sgws** [comment]
Fixed and raised PR https://github.com/hlxsites/sgws-creative/pull/145
