### ISSUE TITLE
Food pairing icons should have animations too

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#130]
http://localhost:3000/bloominbrands/p/1-top-draft
Get this to animate...
![image](https://github.com/hlxsites/sgws-creative/assets/7156029/ee91f398-2ff9-4e99-8273-97202c02c112)

**Comment by atopper** [comment]
Starting this one.  Expecting some `animate` class is being missed.

**Comment by atopper** [comment]
I think the effort to have 3 svg positioned perfectly to create the illusion of 1 icon is stopping any animation.  I'm wondering if I can combine the 3 svgs into 1 to simplify things.
