### ISSUE TITLE
Vertical Selector alignment and styling issue

### ISSUE THREAD

**Issue by allentsliu** [hlxsites/sgws-creative#136]
Vertical Selector has the following issue
- video image is oversized
- the tabs are overlapping with video
- the tabs are missing styling

![Screen Shot 2023-07-12 at 9 50 23 AM](https://github.com/hlxsites/sgws-creative/assets/32020804/aecf0b40-31af-496a-ae83-ac48e1234407)

**Comment by ketansahugit** [comment]
Hi @allentsliu,

Thank you for reporting this issue with the Vertical Selector. I've taken note of the problems you mentioned and I'm interested in working on this issue and resolving these alignment and styling issues. Could you please assign this issue to me? I'll start working on it right away.

**Comment by allentsliu** [comment]
@ketansahugit 
I have assigned it to you. Thank you for looking into it!

**Comment by atopper** [comment]
I'll have this fixed shortly.  Didn't realize there was an issue already.

The line `max-height: 45vw;` has to be removed in the vertical-selector.css file:
```
.vertical-selector .fragment-viewer *.vs-active {
  min-height: 45vw;
  max-height: 45vw;
```

**Comment by atopper** [comment]
@ketansahugit
I tried to put you as a reviewer, but couldn't find your name...
https://github.com/hlxsites/sgws-creative/pull/137

**Comment by ketansahugit** [comment]
Hi @atopper , 
If you are talking about my GitHub user name to assign me the reviewer tag, then its "ketansahugit".

**Comment by atopper** [comment]
Not enough access yet?
![image](https://github.com/hlxsites/sgws-creative/assets/7156029/d04e00bd-a4f8-479c-8ab6-0f26dd65397a)

**Comment by ketansahugit** [comment]
Do you have any idea why it isn't showing my username? Thank you

**Comment by allentsliu** [comment]
@tmathern probably has permission to add @ketansahugit  as reviewer to PRs?

**Comment by tmathern** [comment]
You can always comment without being a reviewer.

**Comment by tmathern** [comment]
In the meantime, I think the issue was resolved.
