### ISSUE TITLE
Add style to push down a background

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#152]
For https://sgcreative.southernglazers.com/bloominbrands/p/5.

What we have:
<img width="1664" alt="Screenshot 2023-07-17 at 4 09 20 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/e3e2051f-46b0-44d6-9ac9-46a7059e0d9a">

What we want:
<img width="1664" alt="Screenshot 2023-07-17 at 4 10 42 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/ce8f11c7-5aa0-4955-b3d1-8da13f60ad37">

Add some padding somewhere so the background goes down, and the video gest mostly a white background.

**Comment by atopper** [comment]
Underway...
