### ISSUE TITLE
Block: brand-news

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#154]
For https://sgcreative.southernglazers.com/bloominbrands/p/8

<img width="1356" alt="Screenshot 2023-07-17 at 4 36 51 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/f841d6f7-68a9-487b-821b-d3fc61c61f97">

1 tall image on left, 2 smaller next to it, and text.

**Comment by sarav-sgws** [comment]
Analyzing this new block requirement
