### ISSUE TITLE
Video button appears but video is already playing

### ISSUE THREAD

**Issue by atopper** [hlxsites/sgws-creative#162]
On page https://sgcreative.southernglazers.com/bloominbrands/p/8, there is a video on top.  It auto-plays.
On page https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/8, there is a video on top and it auto-plays as well, but shows a play button on top of it.  Clicking it seems to unmute the sound...  The play button should not be shown for auto-play videos.

![image](https://github.com/hlxsites/sgws-creative/assets/7156029/31c499df-2f51-4ce3-b20b-7c8ba73622d2)

**Comment by tmathern** [comment]
Actually it seems to be the button from the sliders...
Adding `position: relative` to `.vertical-selector .fragment-viewer .video-group` fixes this.
