### ISSUE TITLE
Author: Blindfold product page

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#17]
https://sgcreative.southernglazers.com/bloominbrands/p/5

**Comment by atopper** [comment]
Underway: 
https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5
[https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/souther[…]x?d=w6dea8d2b7d704b7e9680a82eadc7096b&csf=1&web=1&e=acKNJe](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/bloominbrands/p/5.docx?d=w6dea8d2b7d704b7e9680a82eadc7096b&csf=1&web=1&e=acKNJe)

**Comment by atopper** [comment]
Submitted a PR with a few fixes with this one, and it closed the issue.  Note quick done yet.

**Comment by tmathern** [comment]
LGTM - will open an issue to add a style to "push down" the background.
