### ISSUE TITLE
Author: Ruffino product page

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#18]
https://sgcreative.southernglazers.com/bloominbrands/p/6

Target: https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6

**Comment by atopper** [comment]
https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/6

Fragment Author: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/products/[ruffino.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/southernglazers/sgws-creative/products/ruffino.docx?d=wa64342087eb046818996f01ca67ed47d&csf=1&web=1&e=WOzGLF)?d=wa64342087eb046818996f01ca67ed47d&csf=1&web=1&e=WOzGLF

**Comment by tmathern** [comment]
Will benefit from bugfixes coming in with https://github.com/hlxsites/sgws-creative/pull/150

**Comment by tmathern** [comment]
Will also need https://github.com/hlxsites/sgws-creative/issues/152.
But otherwise, LGTM.

**Comment by tmathern** [comment]
Reopening as the sliders' content still needs authoring. Related to https://github.com/hlxsites/sgws-creative/issues/122
