### ISSUE TITLE
Landing page Portfolio: Background does not cover all portfolio

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#181]
- Background does not cover all portfolio
- Background should not have opacity 50%
<img width="1659" alt="Screenshot 2023-07-24 at 10 26 38 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/fd8b2beb-4765-40b1-babe-d53b37f10f02">

**Comment by allentsliu** [comment]
Thanks @LeonardoLopesHonda! Assigned the issue to you.

**Comment by tmathern** [comment]
@LeonardoLopesHonda How is it going? Any update on this?

**Comment by LeonardoLopesHonda** [comment]
I'm still configuring it, just got time to start seeing the problem now

**Comment by LeonardoLopesHonda** [comment]
I found the opacity problem on line 436 in the styles.css file, I commented the opacity 50% and it got no transparency, I'm still seeing the background size problem.
![image](https://github.com/hlxsites/sgws-creative/assets/83879739/d6144e2d-afc2-4459-8a08-6d42df8de1cd)

**Comment by LeonardoLopesHonda** [comment]
I was able to make the image cover all the content, but the image will be stretched:
![image](https://github.com/hlxsites/sgws-creative/assets/83879739/8a784adb-21da-4a75-80a9-e24eac293197)

**Comment by tmathern** [comment]
> I was able to make the image cover all the content, but the image will be stretched: ![image](https://user-images.githubusercontent.com/83879739/256018914-8a784adb-21da-4a75-80a9-e24eac293197.png)

Can you try using something like "object-fit: cover"?

**Comment by LeonardoLopesHonda** [comment]
> Can you try using something like "object-fit: cover"?

"object-fit: cover" I thought it got more stretched, instead I've user "object-fit: fill"

Cover:
![image](https://github.com/hlxsites/sgws-creative/assets/83879739/4ffbdf1f-0d81-457a-be74-b66e6a502a25)


Fill:
![image](https://github.com/hlxsites/sgws-creative/assets/83879739/20ce5e3f-5d48-4a00-b92f-14f92400f988)

**Comment by LeonardoLopesHonda** [comment]
"object-fit: cover;" looks better?

**Comment by LeonardoLopesHonda** [comment]
I forgot the 'npm run lint'

**Comment by LeonardoLopesHonda** [comment]
I didn't understand how the example link is generated
