### ISSUE TITLE
Stats is not using primary/secondary colors

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#190]
<img width="1645" alt="Screenshot 2023-07-24 at 4 22 24 PM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/771dc968-3167-4db3-a9b8-926c1f956237">

https://main--sgws-creative--hlxsites.hlx.page/bloominbrands/p/5

**Comment by allentsliu** [comment]
fixed the authoring issue
