### ISSUE TITLE
Block: Map

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#23]
As seen in https://sgcreative.southernglazers.com/bloominbrands/p/2
<img width="1189" alt="map" src="https://github.com/hlxsites/sgws-creative/assets/60901087/fbd20da0-61e5-493d-9e59-bcecd90cdb36">

**Comment by tmathern** [comment]
Depending on how we'll draw charts, this could eventually be a variation of https://github.com/hlxsites/sgws-creative/issues/24

**Comment by atopper** [comment]
I assume the image will always be the same.  We won't allow them to select states and associated text right?  Then we could possibly do it with a listener on the mouse, and see when it hovers over a hotspot.  Tricky with scaling, so this might be a fixed width component?

**Comment by tmathern** [comment]
Actually the library we use for charts (echarts - https://echarts.apache.org/en/index.html) also supports maps. 
Since here we only need to support the USA map, I would reuse what echarts has in the map, and add code to show the logos on tap on that state. The advantage is that it uses less screen real estate (and for us, echarts does the heavy lifting of handling the map).

This will also allow us to have a nice authoring experience - like I imagine the authors having a table with the state names/acronyms in a column, and the logos in another.
