### ISSUE TITLE
Button: "return to homepage"

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#30]
Sticky "return to homepage" button.

<img width="190" alt="Screenshot 2023-05-25 at 10 16 45 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/64f2931f-c85b-4d25-a5f1-9d6f156699a3">
<img width="190" alt="Screenshot 2023-05-25 at 10 16 53 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/d111b54c-e2f7-4984-b704-ae5e21bdbb6b">
<img width="190" alt="Screenshot 2023-05-25 at 10 17 04 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/55712409-8d56-4cf3-881d-8a32f939f208">

**Comment by atopper** [comment]
Authoring - I see a simple "return to home" indicator on the section/page metadata.
