### ISSUE TITLE
Columns block: Navigation help

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#4]
Columns area can contain a trigger for navigation help overlay. 

<img width="991" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/b51802de-cd55-41af-9555-8dbfc6eb1c96">

**Comment by arumsey** [comment]
<img width="1114" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/78676acf-fcfc-447e-9e87-0b98c1297184">

**Comment by atopper** [comment]
Authoring...  Embed a : help : icon in the text.  And finish the block with fragment to show.
I'll have to figure out how to overlay it in the right spot (over the slide, product tabs, etc.)
![image](https://github.com/hlxsites/sgws-creative/assets/7156029/c32b2e9b-1b7b-45a2-8d28-8960b23335b9)

**Comment by atopper** [comment]
Good idea is to have the help as 1 image.  We simply show the image, overlay the "Close" icon and hide the image again when it is clicked.
