### ISSUE TITLE
Slides Block: Product overlay

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#52]
Extends #34 

Clicking on product icon will open an overlay for that product.

<img width="606" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/06e5bee3-d0c6-43a7-bac1-149d279e4f36">

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/9813d5ad-6c44-489e-a57e-41e797788b15)

**Comment by tmathern** [comment]
Note: not all products have the "product pairing" icon+overlay.

**Comment by atopper** [comment]
Few things I noticed:
- Outback doesn't have the icon to open the pairing view
- once a pairing view is opened, it should remain open when the carrousel (_left/right 3 of 5_) is used to navigate away and back to it.  I believe it has to be part of the carrousel.

Pair view consists of:

1. meal image
2. bottle image (probably already in the original view - so could we reuse?)
3. Header 1: `A PERFECT PAIRING:`
4. Header 2: Wine + meal
5. Horizontal SVG line (_can we use < HR />?_)
6. Description: text of why it is so great
