### ISSUE TITLE
Slides Block: Program overlay triangle badge and programs loading

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#53]
Extends #34 

Clicking the suggested programs badge will open an overlay of additional program slides (to be loaded as fragments and displayed over the product slides).

<img width="897" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/8c929490-820d-45a2-81ee-4b7ccfb06ca0">

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/30fcebc0-307d-4aec-83c0-8d9713e375d8)

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/df7bbe35-dec3-4fc9-a2ec-0c6da02814e0)

**Comment by tmathern** [comment]
Use https://github.com/hlxsites/sgws-creative/issues/78 and https://github.com/hlxsites/sgws-creative/issues/79 as fragments to be loaded in the slides.

**Comment by tmathern** [comment]
Code for the overlay triangle is in https://github.com/hlxsites/sgws-creative/pull/69
