### ISSUE TITLE
Styling authored borders 

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#56]
Authors may want to include images of borders that are meant to be displayed between blocks of content. Since these borders are supplied by the author any specific styling that needs to be applied in a generic way. Border styling cannot be brand specific. We will need to determine how many variants of borders there are and they expose these variants through section metadata potentially.

Examples:

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/bd781618-ecbb-4c22-be85-84c3531d82a9)

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/35024c70-9439-4ff4-a73c-a0bcf7bb2001)

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/d8c9e27d-ffad-4eed-abf9-b39011af930a)

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/20f1d73a-8aee-458d-b8cd-4619a218ea52)

![image](https://github.com/hlxsites/sgws-creative/assets/1004204/e93513f4-1763-4302-b70f-87d23427c8c7)

The Carrabba's example will be tricky since the top and bottom borders consist of three SVG elements. We may need to discuss this with SG team to determine how their authors obtain border images.

<img width="1280" alt="image" src="https://github.com/hlxsites/sgws-creative/assets/1004204/b1b3b412-5c2d-434a-a67b-bb381cfaa639">

**Comment by tmathern** [comment]
Done - moved into the slides fragment
