### ISSUE TITLE
Video section

### ISSUE THREAD

**Issue by arumsey** [hlxsites/sgws-creative#6]
Allow a video to take up the full width/height of a section.

**Comment by arumsey** [comment]
If a section only contains a video link it could be auto-blocked into a `video` block that takes up the full width of the section and has autoplay turned on.

A common function could be created in `scripts.js` for creating elements since issues like #9 will also need to create videos too.

**Comment by tmathern** [comment]
For now I'll create a video block, and we can style it accordingly when alone in a section.
This will allow us (the block) to also clearly define what the poster should be.
Issue for video block: https://github.com/hlxsites/sgws-creative/issues/36.

If the poster isn't authorable (which would be surprising), then we'll autoblock.
