### ISSUE TITLE
Horizontal accordion

### ISSUE THREAD

**Issue by tmathern** [hlxsites/sgws-creative#77]
Seems to use a background image/video, which gets replaced with content when an item is selected.
Should use fragments like tabs.

Initial view, with video/default content:
<img width="1416" alt="Screenshot 2023-06-14 at 9 14 31 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/7674f6ec-5260-4291-ac4d-edfacbfa2a75">

Selected view changes:
<img width="1416" alt="Screenshot 2023-06-14 at 9 14 40 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/036dd530-4f36-4fbe-b745-04f0ac5b0abb">

<img width="1416" alt="Screenshot 2023-06-14 at 9 15 17 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/3aab2e63-35a0-467e-83fb-35d8ed97c23f">

<img width="1416" alt="Screenshot 2023-06-14 at 9 15 25 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/70cbd529-02bd-42a1-90eb-e76fcbb81172">

<img width="1416" alt="Screenshot 2023-06-14 at 9 15 33 AM" src="https://github.com/hlxsites/sgws-creative/assets/60901087/07b94ae8-e107-4ad3-bdbc-f973f717ab5b">

Original Page example: https://sgcreative.southernglazers.com/bloominbrands/p/6

**Comment by atopper** [comment]
The top of the view also scrolls to the top of the browser when selected.
